### 
GET http://localhost:3000/user

###
GET http://localhost:3000/user/5f0ab66ebfb73a156c61059e
Content-Type: application/json

###
DELETE http://localhost:3000/user/5dc915119f007d27782d1bfa
### SignUp
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "name": "33333",
    "email": "levy151298@gmail.com",
    "password": "01653659895",
    "role": "user",
    "phone": "01653659895",
    "address": "ktx khu b"
}

### verify
POST http://localhost:3000/user/verify/5f12562cda0e430440567c36
Content-Type: application/json

### login
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "levychuyenvan@gmail.com",
    "password": "01653659895"
}
###profile
GET http://localhost:3000/user/profile/5f12d0fb0f8cd411d4a6189f
Content-Type: application/json

###logout
POST http://localhost:3000/user/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMDFhMWMyY2FiM2I5MjUwOGUwZjI0OSIsImlhdCI6MTU3Nzg2MDkxN30.rHabaUASxiiBuVDuYP4rksFkcQDSPmzktEEqHOvccUs

###reset
POST  http://localhost:3000/user/resetpassword
Content-Type: application/json

{
    "email": "levy151298@gmail.com"
}

###reset
POST  http://localhost:3000/user/reset/5f12d0fb0f8cd411d4a6189f
Content-Type: application/json

{
    "password": "01653659895"
}

###logoutall
POST http://localhost:3000/user/logoutall
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZGY3MzEyMTRkN2Q5MjJkYzRmYWEwMiIsImlhdCI6MTU3NDkyNTcwM30.EaY0w_mOuAqIBtaMfiJMneo3ZITGYJDILPbKRmvUuaQ

### change info user
PATCH  http://localhost:3000/user/changeprofile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMDYyYzg1ZDY4ZTkxMzZhNDBlMDlhMCIsImlhdCI6MTU3NzgxODkyM30.2k2_8HKs1fZILmJBFKqw3Yqp9n2vDm8VrRalljEahlk
{
    "name": "le vy",
    "email": "levy151298@gmail.com"
}

### change password
PATCH http://localhost:3000/user/changepassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMDFhMmIzMjdkMmY3MWQzY2E0ZGY0MiIsImlhdCI6MTU3Nzc5MzU3MX0.P0MTBIyjbwepk235iNhTrtw9Rmh6m1ienpzfI0dsqaA

{
    "password1": "123456",
    "password2": "123456"
}

### Add product
### Neu product thuoc 1 cate thi phai xoa ngoac []
POST  http://localhost:3000/product/add
Content-Type: application/json

{
    "name": "Hitmonchan",
    "desc": "aadav dasd adafasdf",
    "price": "1200",
    "rating": "8",
    "qty": "2",
    "imgurl": "https://i.ibb.co/MMKg9Dk/107-Hitmonchan-Fighting.png",
    "category": [
        {
            "_id": "5e090471e3d81d0e486af33b",
            "name": "Fighting"
        },{
            "_id": "5e09041de3d81d0e486af330",
            "name": "Dragon"
        }
    ]
}

### get product (không có category name)
GET http://localhost:3000/product/v1
Content-Type: application/json

### get product (có category name)
GET http://localhost:3000/product/v2/normal
Content-Type: application/json

###
GET http://localhost:5500/product/5e0ce865c0ef1b255c6f10e8
Content-Type: application/json
###
PATCH  http://localhost:3000/product/5e0cd9e93272931d00d386d0
Content-Type: application/json

{
    "desc": "sản phẩm mới của chúng tôi"
}
###
DELETE  http://localhost:3000/product/5e0cddf0c0ef1b255c6f10c3
Content-Type: application/json

###
POST http://localhost:3000/order/ntf
Content-Type: application/json

###upload image - trong adminpage
POST http://localhost:3000/upload
Content-Type: application/json

{
    "name": "test",
    "imgPath": "c:\\Users\\lynkn\\Desktop\\Mona_Lisa.jpg"
}

###add category
POST http://localhost:3000/category
Content-Type: application/json

{
    "name": "Ground"
}

### reset password
POST http://localhost:5500/user/resetpassword
Content-Type: application/json

{
    "email": "levychuyenvan@gmail.com"
}

### get category by id

GET  http://localhost:3000/category/5e0903ece3d81d0e486af32b
Content-Type: application/json

### get category by name

GET  http://localhost:3000/category/cate/Normal
Content-Type: application/json
### get category
GET  http://localhost:3000/category
Content-Type: application/json
### xác nhận đơn
POST http://localhost:5500/order/vetifi/5f18770c768e4b36980ab491
Content-Type: application/json

### post order
POST http://localhost:3000/order/add
Content-Type: application/json

{
    "productid": ["5e0cec0bc0ef1b255c6f10f4"],
    "quantity": [ 1 ],
    "userid": "5f140b3ef2c61d2b648395f8",
    "phone": "0353659895",
    "address": "ktx khu b",
    "email": "levychuyenvan@gmail.com"
}

### patch order
PATCH http://localhost:5500/order/5f191760421aa30030b58474
Content-Type: application/json

{
    "phone": "0353659895",
    "address": "ktx khu b",
    "email": "levy151298@gmail.com"
}

### get order by id
Get http://localhost:3000/order/5f0abf7ec963e538480df52b
Content-Type: application/json

### get order by user

Get http://localhost:3000/order/user/5f0ab66ebfb73a156c61059e
Content-Type: application/json

### get order
Get http://localhost:3000/order
Content-Type: application/json

### post rate
POST http://localhost:5500/rating
Content-Type: application/json

{
    "productID": "5e0cdea3c0ef1b255c6f10c6",
    "rate": 6,
    "userID": "5f16f62c55c37700302b335f",
    "content": "đẹp nha, hihi"
}
### get rating by id
Get http://localhost:3000/rating/5e0cec0bc0ef1b255c6f10f4
Content-Type: application/json

### get rating by user
Get http://localhost:3000/rating/user/5f0ab66ebfb73a156c61059e
Content-Type: application/json

### get rating by product
Get http://localhost:3000/rating/product/5e0ceb2ec0ef1b255c6f10f2
Content-Type: application/json

### patch rating
PATCH  http://localhost:3000/rating/5f16f8c055c37700302b3365
Content-Type: application/json

{
    "rate": 9,
    "content": "đẹp, hihi"
}

### post message
POST http://localhost:5500/noty
Content-Type: application/json

{
    "UserID": "5f0ab66ebfb73a156c61059e",
    "message": "chào shop"
}

### get mess by user
Get http://localhost:5500/noty/user/5f0ab66ebfb73a156c61059e
Content-Type: application/json

### get mess
Get http://localhost:5500/noty/
Content-Type: application/json
